[project]
name = "vertex-ai-job"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-cloud-aiplatform>=1.84.0",
    "google-cloud-storage>=2.19.0",
    "invoke>=2.2.0",
]
